"""Add AI fields to Issue model

Revision ID: 9435a4f03b05
Revises: 
Create Date: 2025-08-02 15:59:50.312713

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9435a4f03b05'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('integration_tokens',
    sa.Column('provider', sa.String(), nullable=False),
    sa.Column('access_token', sa.String(), nullable=False),
    sa.Column('refresh_token', sa.String(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('provider')
    )
    op.create_table('issues',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('severity', sa.Integer(), nullable=True),
    sa.Column('frequency', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('tags', sa.String(), nullable=True),
    sa.Column('jira_issue_key', sa.String(), nullable=True),
    sa.Column('hubspot_ticket_id', sa.String(), nullable=True),
    sa.Column('ai_enabled', sa.Boolean(), nullable=True),
    sa.Column('ai_sentiment', sa.String(), nullable=True),
    sa.Column('ai_urgency', sa.Float(), nullable=True),
    sa.Column('ai_category', sa.String(), nullable=True),
    sa.Column('ai_tags', sa.String(), nullable=True),
    sa.Column('ai_severity_confidence', sa.Float(), nullable=True),
    sa.Column('ai_sentiment_confidence', sa.Float(), nullable=True),
    sa.Column('ai_category_confidence', sa.Float(), nullable=True),
    sa.Column('ai_severity_reasoning', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_issues_ai_category', 'issues', ['ai_category'], unique=False)
    op.create_index('ix_issues_ai_sentiment', 'issues', ['ai_sentiment'], unique=False)
    op.create_index('ix_issues_hubspot_tenant', 'issues', ['tenant_id', 'hubspot_ticket_id'], unique=False)
    op.create_index(op.f('ix_issues_hubspot_ticket_id'), 'issues', ['hubspot_ticket_id'], unique=False)
    op.create_index('ix_issues_tenant_created', 'issues', ['tenant_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_issues_tenant_id'), 'issues', ['tenant_id'], unique=False)
    op.create_index('ix_issues_tenant_severity', 'issues', ['tenant_id', 'severity'], unique=False)
    op.create_index('ix_issues_tenant_source', 'issues', ['tenant_id', 'source'], unique=False)
    op.create_index('ix_issues_tenant_status', 'issues', ['tenant_id', 'status'], unique=False)
    op.create_table('sync_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('integration_id', sa.UUID(), nullable=False),
    sa.Column('event_type', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('items_processed', sa.Integer(), nullable=True),
    sa.Column('items_created', sa.Integer(), nullable=True),
    sa.Column('items_updated', sa.Integer(), nullable=True),
    sa.Column('items_deleted', sa.Integer(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('error_details', sa.JSON(), nullable=True),
    sa.Column('source_data', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sync_events_integration_id'), 'sync_events', ['integration_id'], unique=False)
    op.create_index(op.f('ix_sync_events_tenant_id'), 'sync_events', ['tenant_id'], unique=False)
    op.create_table('tenant_integrations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('integration_type', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('config', sa.JSON(), nullable=False),
    sa.Column('last_synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_sync_status', sa.String(), nullable=True),
    sa.Column('sync_error_message', sa.String(), nullable=True),
    sa.Column('webhook_url', sa.String(), nullable=True),
    sa.Column('webhook_secret', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tenant_integrations_tenant_id'), 'tenant_integrations', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tenant_integrations_tenant_id'), table_name='tenant_integrations')
    op.drop_table('tenant_integrations')
    op.drop_index(op.f('ix_sync_events_tenant_id'), table_name='sync_events')
    op.drop_index(op.f('ix_sync_events_integration_id'), table_name='sync_events')
    op.drop_table('sync_events')
    op.drop_index('ix_issues_tenant_status', table_name='issues')
    op.drop_index('ix_issues_tenant_source', table_name='issues')
    op.drop_index('ix_issues_tenant_severity', table_name='issues')
    op.drop_index(op.f('ix_issues_tenant_id'), table_name='issues')
    op.drop_index('ix_issues_tenant_created', table_name='issues')
    op.drop_index(op.f('ix_issues_hubspot_ticket_id'), table_name='issues')
    op.drop_index('ix_issues_hubspot_tenant', table_name='issues')
    op.drop_index('ix_issues_ai_sentiment', table_name='issues')
    op.drop_index('ix_issues_ai_category', table_name='issues')
    op.drop_table('issues')
    op.drop_table('integration_tokens')
    # ### end Alembic commands ###
